import type {Basics} from './schema';
import {dayDate} from './schema';
import type {Catalog} from '../data/catalog';
export function destinationFor(b:Basics,day:number){return b.destinations?.find(d=>d.startDay<=day&&d.endDay>=day);}
export function dayWindow(b:Basics,day:number){const tz=destinationFor(b,day)?.timezone??b.timezone;return {start:Date.parse(localInstant(dayDate(b,day),0,tz)),end:Date.parse(localInstant(dayDate(b,day),1440,tz))};}
export function transferForTransition(b:Basics,day:number){
 const before=destinationFor(b,day-1),after=destinationFor(b,day);if(!before||!after||before.region===after.region)return {transfer:undefined,ambiguous:false};
 const start=dayWindow(b,day-1).start,end=dayWindow(b,day).end;
 const matches=(b.transfers??[]).filter(t=>t.fromRegion===before.region&&t.toRegion===after.region&&(t.arrivalDay===undefined||t.arrivalDay===day)&&Date.parse(t.arrival)>Date.parse(t.departure)&&Date.parse(t.arrival)>=Math.min(start,end)&&Date.parse(t.departure)<Math.max(start,end)&&Date.parse(t.arrival)<=Math.max(start,end));
 return {transfer:matches.length===1?matches[0]:undefined,ambiguous:matches.length>1};
}
export function isTravelOnlyDay(b:Basics,day:number){if(!b.transfers?.length)return false;try{const {start,end}=dayWindow(b,day);return (b.transfers??[]).some(t=>{const departure=Date.parse(t.departure),arrival=Date.parse(t.arrival);return arrival>departure&&(departure<=start&&arrival>=end||b.travelDays?.includes(day)&&departure<end&&arrival>start);});}catch{return false;}}
const instantCache=new Map<string,string>();
export function localInstant(date:string,minutes:number,timezone:string){const cacheKey=date+'|'+minutes+'|'+timezone,cached=instantCache.get(cacheKey);if(cached)return cached;const desired=Date.parse(date+'T00:00:00Z')+minutes*60000;let guess=desired;const formatter=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});const shown=(timestamp:number)=>{const p=Object.fromEntries(formatter.formatToParts(timestamp).map(v=>[v.type,v.value]));return Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute),Number(p.second));};for(let i=0;i<5;i++){const delta=desired-shown(guess);if(!delta)break;guess+=delta;}if(shown(guess)!==desired)throw Error('존재하지 않는 현지 시간입니다. 일광절약시간 전환 날짜를 확인해 주세요.');if(shown(guess-3600000)===desired||shown(guess+3600000)===desired)throw Error('중복되는 현지 시간입니다. 시간대 오프셋을 직접 확인해 주세요.');const result=new Date(guess).toISOString();if(instantCache.size>=4096)instantCache.delete(instantCache.keys().next().value!);instantCache.set(cacheKey,result);return result;}
export function freshAt(at:string|null|undefined,maxAge:number,now=Date.now()){const time=at?Date.parse(at):NaN;return Number.isFinite(time)&&time<=now&&now-time<=maxAge;}
export function convertMoney(value:number,from:string,to:string,catalog:Catalog):number|null{if(from===to)return value;const fx=catalog.fx;if(!fx||!freshAt(fx.at,7*86400000))return null;const a=from===fx.base?1:fx.rates[from],b=to===fx.base?1:fx.rates[to];return a&&b?value/a*b:null;}
export function mergeCatalog(a:Catalog,b:Catalog):Catalog{if(a.mode!=='real'||b.mode!=='real')throw Error('실제 도시만 합칠 수 있습니다.');const cities=[...(a.cities??[]),...(b.cities??[])].filter((c,i,all)=>all.findIndex(v=>v.region===c.region)===i);if(cities.length>10)throw Error('여행에는 도시 10개까지 추가할 수 있습니다.');const places=[...a.places,...b.places].filter((p,i,all)=>all.findIndex(q=>q.id===p.id)===i);if(places.length>2000)throw Error('후보 장소 한도에 도달했습니다.');return {...a,region:cities.map(c=>c.region).join(' · ').slice(0,120),cities,places,routes:[...a.routes,...b.routes].filter((r,i,all)=>all.findIndex(v=>v.id===r.id)===i),fx:b.fx??a.fx,collectedAt:b.collectedAt,sourceNotice:'실제 다도시 자료 · © OpenStreetMap 기여자 / ODbL · 도시 간 이동·운영 정보는 별도 확인이 필요합니다.'};}
export const transportLabel={taxi:'택시',walk:'도보',driving:'자동차',transit:'대중교통'};
export function money(value:number,currency='KRW'){return new Intl.NumberFormat('ko-KR',{style:'currency',currency,maximumFractionDigits:2}).format(value);}
