import {GET as operationalGET} from '../src/app/api/ops/route';
import {afterAll,afterEach,beforeAll,expect,it,vi} from 'vitest';
import {database,rpc} from '../scripts/test-store.mjs';
import {issueAccount,accountOf,AuthProvider,roleOf,ACCOUNT_COOKIE} from '../src/server/account';
import {ownerOf,issueSession,hash} from '../src/server/security';
import {verifyBot} from '../src/server/bot';
import {approvePlace,assertProofs,verificationKey,validProof} from '../src/server/verification';
import {verifyReviewed,isReviewed} from '../src/domain/verification';
import {osmCatalog} from '../src/adapters/real-data';
import {recordVenue} from '../src/domain/venue-facts';
let db:any;beforeAll(async()=>{db=await database();},20000);afterAll(async()=>db.close());afterEach(()=>vi.unstubAllEnvs());
const secret='isolated-signing-key-not-a-production-secret';
it('signed accounts cannot be forged or used after expiry and never fall back to anonymous ownership',()=>{vi.stubEnv('BOPok_SESSION_SECRET',secret);const account={id:'00000000-0000-4000-8000-000000000001',email:'test@example.org',exp:Math.floor(Date.now()/1000)+1800};const value=issueAccount(account);const request=new Request('https://example.org',{headers:{cookie:`${ACCOUNT_COOKIE}=${value}; bopok_session=${issueSession()}`}});expect(accountOf(request)?.id).toBe(account.id);expect(ownerOf(request)).toBe(hash('account:'+account.id));expect(accountOf(request,Date.now()+3600000)).toBeNull();expect(ownerOf(new Request(request,{headers:{cookie:`${ACCOUNT_COOKIE}=${value.slice(0,-3)}abc; bopok_session=${issueSession()}`}}))).toBeNull();vi.stubEnv('BOPok_REVIEWER_IDS',account.id);expect(roleOf(account,'reviewer')).toBe(true);expect(roleOf({...account,id:'00000000-0000-4000-8000-000000000002'},'reviewer')).toBe(false);});
it('provider identity is verified with its user endpoint rather than trusting a client supplied user id',async()=>{const calls:string[]=[];const fetcher=vi.fn(async(url:any)=>{calls.push(String(url));return Response.json(calls.length===1?{access_token:'access',refresh_token:'refresh',expires_in:7200,user:{id:'forged'}}:{id:'00000000-0000-4000-8000-000000000001',email:'verified@example.org'});}) as typeof fetch;const session=await new AuthProvider('https://example.supabase.co','public-anon',fetcher).verify('verified@example.org','123456');expect(session.account.email).toBe('verified@example.org');expect(session.account.exp).toBeLessThanOrEqual(Date.now()/1000+3600);expect(calls[1]).toContain('/auth/v1/user');});
it('anonymous trips are claimed atomically by the verified account and old recovery credentials are invalidated',async()=>{const previous='a'.repeat(64),owner='b'.repeat(64);const t=await rpc(db,'bopok_trip',{p_action:'create',p_owner:previous,p_payload:{id:'claim-me'}});await rpc(db,'bopok_identity',{p_action:'set',p_owner:previous,p_hash:'c'.repeat(64)});expect((await rpc(db,'bopok_claim',{p_owner:owner,p_previous:previous})).claimed).toBe(1);expect((await rpc(db,'bopok_trip',{p_action:'get',p_owner:owner,p_id:t.id})).role).toBe('owner');expect((await rpc(db,'bopok_trip',{p_action:'get',p_owner:previous,p_id:t.id})).error).toBe('forbidden');expect((await rpc(db,'bopok_identity',{p_action:'recover',p_hash:'c'.repeat(64)})).owner).toBeUndefined();});
it('review approval forbids self approval, preserves original facts and signatures detect import or storage tampering',async()=>{vi.stubEnv('BOPok_SESSION_SECRET',secret);const at=new Date().toISOString(),place=recordVenue(osmCatalog('서울',{elements:[{type:'node',id:1,lat:37.5,lon:127,tags:{name:'공원',leisure:'park'}}]},at).places[0],{source:'https://example.org/facility',at,walkMin:5,walkM:100,stairs:false,seat:true,cost:0,foods:null});const submitted=await rpc(db,'bopok_review',{p_action:'submit',p_owner:'d'.repeat(64),p_payload:{placeId:place.id,placeName:place.name,place}});expect((await rpc(db,'bopok_review',{p_action:'approve',p_owner:'d'.repeat(64),p_id:submitted.id})).error).toBe('self_review');expect((await rpc(db,'bopok_review',{p_action:'approve',p_owner:'e'.repeat(64),p_id:submitted.id})).status).toBe('approved');const approved=approvePlace(place,submitted.id);expect(validProof(approved)).toBe(true);expect(isReviewed(approved)).toBe(false);expect(await verifyReviewed(approved,verificationKey())).toBe(true);expect(isReviewed(approved)).toBe(true);const changed=structuredClone(approved);changed.walkMin.value=0;expect(validProof(changed)).toBe(false);expect(isReviewed(changed)).toBe(false);expect(()=>assertProofs([changed])).toThrow();});
it('bot verification fails closed on wrong hostname/action or reused failed challenge',async()=>{vi.stubEnv('BOPok_APP_URL','https://example.org');vi.stubEnv('BOPok_TURNSTILE_SECRET','isolated-bot-key');const fetcher=(data:any)=>(async()=>Response.json(data)) as typeof fetch;expect(await verifyBot('token','account',fetcher({success:true,hostname:'evil.org',action:'account'}))).toBe(false);expect(await verifyBot('token','account',fetcher({success:true,hostname:'example.org',action:'paid'}))).toBe(false);expect(await verifyBot('token','account',fetcher({success:true,hostname:'example.org',action:'account'}))).toBe(true);expect(await verifyBot('', 'account',fetcher({success:true}))).toBe(false);});

it('operational data stays private even when a malformed unicode token matches the secret character length',async()=>{vi.stubEnv('BOPok_OPS_SECRET','a'.repeat(32));const response=await operationalGET(new Request('https://example.org/api/ops',{headers:{authorization:'Bearer '+'a'.repeat(31)+'é'}}));expect(response.status).toBe(403);});
