'use client';
import {useEffect,useRef,useState} from 'react';
import Script from 'next/script';
declare global{interface Window{turnstile?:{render:(element:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void};}}
export default function AccountPanel(){const [state,setState]=useState<{configured:boolean;authenticated:boolean;email?:string;botSiteKey?:string}>(),[email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[botToken,setBotToken]=useState('');const container=useRef<HTMLDivElement>(null),widget=useRef<string|null>(null);
 const load=async()=>{try{let data=await fetch('/api/account').then(r=>r.json());if(data.refreshNeeded){const refreshed=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});if(refreshed.ok)data=await fetch('/api/account').then(r=>r.json());}setState(data);}catch{setMessage('계정 상태를 읽지 못했습니다.');}};
 useEffect(()=>{load();return ()=>{if(widget.current)window.turnstile?.remove(widget.current);};},[]);
 function render(){if(container.current&&window.turnstile&&!widget.current)widget.current=window.turnstile.render(container.current,{sitekey:state?.botSiteKey,action:'account',callback:(v:string)=>setBotToken(v),'expired-callback':()=>setBotToken(''),'error-callback':()=>setBotToken('')});}
 async function action(action:string){setBusy(true);setMessage('');try{const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(action==='request'||action==='verify'?{email}:{}),...(action==='verify'?{code}:{}),...(action==='request'&&botToken?{botToken}:{})})});const data=await r.json();if(!r.ok)throw Error(data.error);setCode('');setBotToken('');if(widget.current)window.turnstile?.reset(widget.current);if(action==='request'){setSent(true);setMessage('이메일의 확인 코드를 입력해 주세요.');}else{setSent(false);await load();window.dispatchEvent(new Event('bopok:identity'));setMessage(action==='logout'?'로그아웃했습니다.':'로그인했습니다. 기존 서버 여행도 계정에 연결했습니다.');}}catch(e){setMessage(e instanceof Error?e.message:'로그인에 실패했습니다.');}finally{setBusy(false);}}
 return <details className="cloud-panel no-print"><summary>계정 로그인</summary>{!state?.configured?<p>계정 연결 설정을 완료하면 이메일 확인 코드로 로그인할 수 있어요.</p>:state.authenticated?<><p>{state.email} 계정으로 로그인했습니다.</p><button className="secondary" disabled={busy} onClick={()=>action('logout')}>로그아웃</button></>:<><label>로그인 이메일<input type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label>{state.botSiteKey&&<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" onReady={render}/><div ref={container}/></>}<button className="secondary" disabled={busy||!email||!!state.botSiteKey&&!botToken} onClick={()=>action('request')}>이메일 확인 코드 받기</button>{sent&&<><label>이메일 확인 코드<input inputMode="numeric" autoComplete="one-time-code" maxLength={10} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="secondary" disabled={busy||code.length<6} onClick={()=>action('verify')}>확인하고 로그인</button></>}</>}{message&&<p role="status">{message}</p>}</details>;
}
