'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import type {CloudTrip} from '../server/store';
import {Trip,tripSchema,time,dayDate} from '../domain/schema';
import {catalogFor,indexCatalog} from '../data/catalog';
import {validateSchedule} from '../domain/validate';
import Bopok from './Bopok';
const options=['좋아요','걷는 구간을 줄여 주세요','쉬는 시간을 늘려 주세요','식사를 바꾸고 싶어요'];
export default function FamilyPage(){const revoked=useRef(false);const [cloud,setCloud]=useState<CloudTrip|null>(null),[token,setToken]=useState(''),[id,setId]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false);
  useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1)),id=params.get('trip')??'',token=params.get('token')??'';setId(id);setToken(token);if(!id||!token){setError('공유 링크가 없거나 올바르지 않습니다.');return;}const controller=new AbortController();let pending=false;const load=async()=>{if(pending||revoked.current)return;pending=true;try{const r=await fetch(`/api/trips/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal});const data=await r.json();if(!r.ok){if([401,403,404].includes(r.status)){revoked.current=true;setCloud(null);setEditing(false);}throw Error(data.error);}tripSchema.parse(data.trip);if(revoked.current)return;setCloud(data);setError('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'여행을 읽지 못했습니다.');}finally{pending=false;}};load();const timer=setInterval(load,5000);return ()=>{controller.abort();clearInterval(timer);};},[]);
  async function feedback(text:string){setBusy(true);try{const r=await fetch(`/api/trips/${id}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'feedback',text})});const data=await r.json();if(!r.ok){if([401,403,404].includes(r.status)){revoked.current=true;setCloud(null);setEditing(false);}throw Error(data.error);}if(revoked.current)return;setCloud(data);setNotice('의견을 기록했어요. 일정을 바로 바꾸지 않고 가족이 수정안을 확인합니다.');}catch(e){setError(e instanceof Error?e.message:'의견을 기록하지 못했습니다.');}finally{setBusy(false);}}
  if(editing&&cloud)return <Bopok initialCloud={cloud} accessToken={token}/>;
  if(!cloud)return <main className="empty"><h1>가족 여행 확인</h1><p role="alert">{error||'여행을 불러오고 있어요.'}</p><Link href="/">보폭 홈으로 돌아가기</Link></main>;
  const trip=cloud.trip,catalog=catalogFor(trip.basics.mode,trip.catalog),{placeById,getRoute}=indexCatalog(catalog),report=validateSchedule(trip.items,trip.conditions,trip.basics,catalog);
  return <main className="workspace parent-sheet parent-mode"><div className="parent-toolbar no-print"><Link href="/">보폭 홈</Link><button className="secondary" onClick={()=>window.print()}>인쇄 / PDF 저장</button>{cloud.role!=='viewer'&&<button className="secondary" onClick={()=>setEditing(true)}>상세 화면에서 일정 수정</button>}</div><h1>{trip.basics.title}</h1><p className="parent-subtitle">{trip.basics.region} · {trip.basics.date}부터 {trip.basics.days}일 · {trip.basics.timezone}</p><div className="demo-banner"><strong>{catalog.sourceNotice}</strong></div>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {Array.from({length:trip.basics.days},(_,n)=><section className="parent-day" key={n}><h2>{n+1}일차 <span>{dayDate(trip.basics,n+1)}</span></h2>{trip.items.filter(i=>i.day===n+1).sort((a,b)=>a.start-b.start).map(i=>{const p=placeById.get(i.placeId??''),r=getRoute(i.fromId,i.toId,i.transport);return <article className="parent-item" key={i.id}><span className="parent-time">{time(i.start)} – {time(i.end)}</span><div><h3>{i.kind==='move'?`${placeById.get(i.fromId??'')?.name??'출발지 미확인'} → ${placeById.get(i.toId??'')?.name??'도착지 미확인'}`:p?.name??'장소 미확인'}</h3><p>{i.kind==='rest'?`${i.end-i.start}분 쉬어요. ${p?.seat.value===true?'자료에 앉을 자리 정보가 있어요.':'앉을 자리를 확인해 주세요.'}`:i.kind==='meal'?'함께 식사해요. 메뉴를 확인해 주세요.':i.kind==='move'?`${i.transport==='walk'?'걸어서':'택시로'} 이동해요. 예상 ${r?.duration.value??'미확인'}분.`:p?.description}</p>{i.kind!=='rest'&&<p>걷는 구간: {i.kind==='move'?r?.walkMin.value??'미확인':p?.walkMin.value??'미확인'}분 · {i.kind==='move'?r?.walkM.value??'미확인':p?.walkM.value??'미확인'}m</p>}</div></article>;})}</section>)}
    <section className="parent-check"><h2>떠나기 전에 확인해요</h2>{report.issues.map((i,n)=><p key={n}>• {i.message}</p>)}</section><section className="parent-feedback no-print"><h2>이 여행, 어떠세요?</h2><p>의견은 서버에 기록되어 다른 기기의 가족 화면에도 표시됩니다.</p><div>{options.map(text=><button className="secondary" disabled={busy} key={text} onClick={()=>feedback(text)}>{text}</button>)}</div></section></main>;
}
