'use client';
import {useState} from 'react';
import {Trip} from '../domain/schema';
import {recordVenue} from '../domain/venue-facts';
import {verifyReviewed} from '../domain/verification';
import {catalogSchema} from '../data/catalog';
export default function VenueFacts({trip,onTrip}:{trip:Trip;onTrip:(t:Trip)=>void}){
 const [id,setId]=useState(''),[message,setMessage]=useState('');if(trip.basics.mode!=='real'||!trip.catalog)return null;
 const place=trip.catalog.places.find(p=>p.id===id)??trip.catalog.places[0];if(!place)return null;
 async function review(action:string){try{if(action==='submit'){const r=await fetch('/api/verification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,place})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('독립 검토를 요청했습니다. 담당자가 원문을 확인한 뒤 승인합니다.');}else{const [r,k]=await Promise.all([fetch('/api/verification'),fetch('/api/verification?mode=key')]);const data=await r.json(),key=await k.json();if(!r.ok)throw Error(data.error);const reviewed=data.reviews.find((row:any)=>row.placeId===place!.id)?.place;if(!reviewed){setMessage('이 장소의 승인된 검토 기록이 없습니다.');return;}if(!await verifyReviewed(reviewed,key.publicKey))throw Error('검토 서명이 올바르지 않습니다.');const catalog=catalogSchema.parse({...trip.catalog,places:trip.catalog!.places.map(p=>p.id===reviewed.id?reviewed:p)});onTrip({...trip,catalog,revision:trip.revision+1});setMessage('독립 검토를 마친 기록으로 갱신했습니다. 최신 운영 정보는 출발 전에 다시 확인해 주세요.');}}catch(e){setMessage(e instanceof Error?e.message:'검토 연결 오류');}}
 function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();try{const data=new FormData(event.currentTarget),number=(key:string)=>String(data.get(key)??'').trim()===''?null:Number(data.get(key)),bool=(key:string)=>data.get(key)==='unknown'?null:data.get(key)==='yes';
  const updated=recordVenue(place!,{source:data.get('source'),at:String(data.get('at'))+'T00:00:00.000Z',walkMin:number('walkMin'),walkM:number('walkM'),cost:number('cost'),stairs:bool('stairs'),seat:bool('seat'),foods:String(data.get('foods')??'').trim()?String(data.get('foods')).split(',').map(s=>s.trim()):null});
  const catalog=catalogSchema.parse({...trip.catalog,places:trip.catalog!.places.map(p=>p.id===updated.id?updated:p)});onTrip({...trip,catalog,revision:trip.revision+1});setMessage('확인 기록을 저장했습니다. 사용자 기록임을 표시하고 조건을 다시 점검합니다. 서버 공유 여행은 서버 변경 저장도 눌러 주세요.');
 }catch{setMessage('HTTPS 출처·확인 날짜·숫자 범위를 확인해 주세요. 빈 숫자는 미확인으로 보관됩니다.');}}
 return <details className="cloud-panel no-print"><summary>출발 전 시설·메뉴 확인 기록</summary><p>기관·장소의 안내 자료를 확인하고 출처와 날짜를 기록하세요. 사용자 기록은 서비스의 검증 결과와 구분하여 표시합니다. 빈 값은 미확인입니다. 비용은 장소에 표시된 현지 통화로 입력합니다.</p><label>확인할 실제 장소<select value={place.id} onChange={e=>{setId(e.target.value);setMessage('');}}>{trip.catalog.places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><form key={`${place.id}:${trip.revision}`} onSubmit={save}>
 <label>확인 자료 HTTPS 주소<input name="source" type="url" required placeholder="https://"/></label><label>자료를 확인한 날짜<input name="at" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label>
 <label>확인한 내부 보행 시간 (분)<input name="walkMin" type="number" min="0" max="180" defaultValue={place.walkMin.value??''}/></label><label>확인한 내부 보행 거리 (m)<input name="walkM" type="number" min="0" max="10000" defaultValue={place.walkM.value??''}/></label>
 <label>계단 정보<select aria-label="계단 정보" name="stairs" defaultValue={place.stairs.value===null?'unknown':place.stairs.value?'yes':'no'}><option value="unknown">미확인</option><option value="yes">계단 있음</option><option value="no">계단 없음</option></select></label><label>앉을 자리<select aria-label="앉을 자리" name="seat" defaultValue={place.seat.value===null?'unknown':place.seat.value?'yes':'no'}><option value="unknown">미확인</option><option value="yes">있음</option><option value="no">없음</option></select></label>
 <label>확인한 항목 비용 ({place.currency??'KRW'})<input name="cost" type="number" min="0" max="10000000" defaultValue={place.cost.value??''}/></label><label>확인한 음식 종류 (쉼표로 구분)<input name="foods" defaultValue={place.foods.value?.join(', ')??''} placeholder="순한 음식, 죽"/></label><button className="secondary" type="submit">시설·메뉴 확인 기록 저장</button></form><div className="schedule-actions"><button className="secondary" onClick={()=>review('submit')}>이 기록의 독립 검토 요청</button><button className="secondary" onClick={()=>review('approved')}>승인된 기록 불러오기</button><a href="/review">담당자 검토 화면</a></div>{message&&<p role="status">{message}</p>}</details>;
}
