import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,basename} from 'node:path';
import {spawn} from 'node:child_process';
import {pathToFileURL} from 'node:url';
const magic=Buffer.from('BOPBK01');
function key(value){if(!/^[a-f0-9]{64}$/i.test(value??''))throw Error('BOPok_BACKUP_KEY must contain 64 hexadecimal characters.');return Buffer.from(value,'hex');}
export function encryptBackup(bytes,value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(value),iv);cipher.setAAD(magic);const ciphertext=Buffer.concat([cipher.update(bytes),cipher.final()]);return Buffer.concat([magic,iv,cipher.getAuthTag(),ciphertext]);}
export function decryptBackup(bytes,value){if(bytes.length<36||!bytes.subarray(0,7).equals(magic))throw Error('Invalid backup.');const cipher=createDecipheriv('aes-256-gcm',key(value),bytes.subarray(7,19));cipher.setAAD(magic);cipher.setAuthTag(bytes.subarray(19,35));return Buffer.concat([cipher.update(bytes.subarray(35)),cipher.final()]);}
function databaseEnvironment(value){const u=new URL(value);if(!['postgres:','postgresql:'].includes(u.protocol)||!u.hostname||!u.pathname.slice(1))throw Error('Database configuration missing.');return {...process.env,PGHOST:u.hostname,PGPORT:u.port||'5432',PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGDATABASE:decodeURIComponent(u.pathname.slice(1)),PGSSLMODE:u.searchParams.get('sslmode')||(!['localhost','127.0.0.1'].includes(u.hostname)?'verify-full':'disable'),PGSSLROOTCERT:u.searchParams.get('sslrootcert')||process.env.PGSSLROOTCERT||(!['localhost','127.0.0.1'].includes(u.hostname)?'system':''),PGCONNECT_TIMEOUT:'10'};}
export async function runPG(command,args,env){let executable=command,arguments_=args,input;const names=['PGHOST','PGPORT','PGUSER','PGPASSWORD','PGDATABASE','PGSSLMODE','PGSSLROOTCERT','PGCONNECT_TIMEOUT'];const container=process.env.BOPok_PG_CLIENT_CONTAINER;if(container){if(!/^[a-zA-Z0-9_.-]+$/.test(container))throw Error('Invalid PostgreSQL client container.');executable='docker';if(names.some(name=>/[\r\n]/.test(env[name]??'')))throw Error('Invalid database configuration.');input=names.map(name=>env[name]??'').join('\n')+'\n';arguments_=['exec','-i',container,'sh','-c',names.map(name=>'IFS= read -r '+name+'; export '+name+';').join('')+'exec "$@"','pg-client',command,...args];}return await new Promise((resolve,reject)=>{const child=spawn(executable,arguments_,{env,stdio:['pipe','pipe','pipe']});const output=[],errors=[];let length=0;child.stdout.on('data',chunk=>{length+=chunk.length;if(length>1024*1024*1024){child.kill();reject(Error('Backup exceeds 1 GiB.'));}else output.push(chunk);});child.stdin.end(input);child.stderr.on('data',chunk=>{if(process.env.BOPok_ISOLATED_TEST==='true')errors.push(chunk);});child.on('error',()=>reject(Error('PostgreSQL client unavailable.')));child.on('exit',code=>{if(code===0)return resolve(Buffer.concat(output));if(errors.length){let diagnostic=Buffer.concat(errors).toString();for(const value of [env.PGPASSWORD,env.PGUSER,env.PGHOST])if(value)diagnostic=diagnostic.split(value).join('[redacted]');console.error(diagnostic.slice(0,1500));}reject(Error(command+' failed (exit '+code+'); database credentials were omitted from logs.'));});});}
export async function backup(output,database=process.env.BOPok_DATABASE_URL,secret=process.env.BOPok_BACKUP_KEY){const bytes=await runPG('pg_dump',['--format=custom','--no-owner','--schema=public'],databaseEnvironment(database));const encrypted=encryptBackup(bytes,secret);await writeFile(output,encrypted,{mode:0o600,flag:'wx'});return {bytes:encrypted.length};}
export async function restore(input,database=process.env.BOPok_RESTORE_DATABASE_URL,secret=process.env.BOPok_BACKUP_KEY){const bytes=decryptBackup(await readFile(input),secret),env=databaseEnvironment(database);const count=await runPG('psql',['-X','-At','-v','ON_ERROR_STOP=1','-c',"select (select count(*) from pg_catalog.pg_class where relnamespace='public'::regnamespace)+(select count(*) from pg_catalog.pg_proc where pronamespace='public'::regnamespace)+(select count(*) from pg_catalog.pg_type where typnamespace='public'::regnamespace);"],env);if(count.toString().trim()!=='0')throw Error('Restore target must be an empty database.');const directory=await mkdtemp(join(tmpdir(),'bopok-restore-'));try{const file=join(directory,'verified.dump');await writeFile(file,bytes,{mode:0o600});if(process.env.BOPok_PG_CLIENT_CONTAINER){const container=process.env.BOPok_PG_CLIENT_CONTAINER,remote='/tmp/'+basename(directory)+'.dump';await new Promise((resolve,reject)=>{const child=spawn('docker',['cp',file,container+':'+remote],{env,stdio:'ignore'});child.on('error',reject);child.on('exit',c=>c===0?resolve():reject(Error('Restore transfer failed.')));});try{await runPG('pg_restore',['--clean','--if-exists','--no-owner','--single-transaction','--exit-on-error','--dbname',env.PGDATABASE,remote],env);}finally{await runPG('rm',['-f',remote],env);}}else await runPG('pg_restore',['--clean','--if-exists','--no-owner','--single-transaction','--exit-on-error','--dbname',env.PGDATABASE,file],env);return {restored:true};}finally{await rm(directory,{recursive:true,force:true});}}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){try{const [action,file]=process.argv.slice(2);if(!file||!['backup','restore'].includes(action))throw Error('Usage: node scripts/backup.mjs backup|restore PATH');console.log(JSON.stringify(await (action==='backup'?backup(file):restore(file))));}catch(error){console.error(error.message);process.exitCode=1;}}
