// Isolated PostgreSQL test fixture. Never imported by the application.
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
export const signatures={bopok_trip:['p_action','p_owner','p_id','p_token','p_payload','p_expected','p_role'],bopok_reserve:['p_subject','p_tokens','p_cost','p_minute_limit','p_daily_requests','p_daily_tokens','p_daily_cost','p_scope'],bopok_cache:['p_key','p_value'],bopok_geo_guard:['p_provider'],bopok_identity:['p_action','p_owner','p_hash'],bopok_provider:['p_action','p_name','p_fingerprint','p_ok','p_code'],bopok_health:['p_required'],bopok_metric:['p_event','p_code','p_value'],bopok_maintenance:[],bopok_claim:['p_owner','p_previous'],bopok_review:['p_action','p_owner','p_id','p_payload'],bopok_alert:['p_action'],bopok_backup_record:[]};
export async function database(){const db=new PGlite();await db.exec('create role service_role; create role anon;');await db.exec(await readFile(new URL('../supabase/migrations/001_bopok.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/003_audit_fixes.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/005_readiness_operations.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/006_accounts_reviews.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/007_operations_final.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/009_capacity.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/010_final_readiness.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/011_quota_scopes.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/012_provider_readiness.sql',import.meta.url),'utf8'));return db;}
export async function rpc(db,name,args){if(!signatures[name])throw Error('Unknown RPC');const keys=signatures[name].filter(k=>Object.hasOwn(args,k));const values=keys.map(k=>typeof args[k]==='object'&&args[k]!==null?JSON.stringify(args[k]):args[k]);const result=await db.query(`select public.${name}(${keys.map((k,i)=>`${k} => $${i+1}`).join(',')}) as value`,values);return result.rows[0].value;}
if(process.argv[1]?.endsWith('test-store.mjs')){const db=await database();createServer(async(req,res)=>{if(req.url==='/health'){res.end('ready');return;}try{let body='';for await(const chunk of req){body+=chunk;if(body.length>8500000)throw Error('Large');}const args=body?JSON.parse(body):{};res.setHeader('Content-Type','application/json');
 if(req.url.startsWith('/auth/v1/')){
  if(req.headers.apikey!=='isolated-anon-key'){res.writeHead(401).end();return;}
  const email=req.url.startsWith('/auth/v1/user')?Buffer.from((req.headers.authorization??'').replace('Bearer access.',''),'base64url').toString():req.url.startsWith('/auth/v1/token')?Buffer.from(String(args.refresh_token).replace('refresh.',''),'base64url').toString():args.email;
  if(!/^[a-z+0-9-]+@test\.invalid$/.test(email??'')||req.url==='/auth/v1/verify'&&args.token!=='000000'){res.writeHead(403).end(JSON.stringify({error:'isolated auth rejected'}));return;}
  const id=email.startsWith('reviewer')?'00000000-0000-4000-8000-000000000002':email.startsWith('operator')?'00000000-0000-4000-8000-000000000003':'00000000-0000-4000-8000-000000000001',user={id,email},encoded=Buffer.from(email).toString('base64url');
  res.end(JSON.stringify(req.url==='/auth/v1/otp'?{}:req.url==='/auth/v1/user'?user:{access_token:'access.'+encoded,refresh_token:'refresh.'+encoded,expires_in:3600,user}));return;
 }
 if(req.headers.apikey!=='isolated-test-key'||req.headers.authorization!=='Bearer isolated-test-key'){res.writeHead(401).end();return;}
 res.end(JSON.stringify(await rpc(db,req.url.split('/').at(-1),args)));
 }catch{res.writeHead(500).end('fixture RPC error');}}).listen(Number(process.env.BOPok_TEST_PORT??3155),'127.0.0.1',()=>console.log('Isolated database fixture ready'));}
