import {quotaLimit} from '../../../server/config';
import {z} from 'zod';
import {placeSchema} from '../../../data/catalog';
import {accountOf,roleOf} from '../../../server/account';
import {approvePlace,verificationKey} from '../../../server/verification';
import {configuredRPC,TripStore} from '../../../server/store';
import {ownerOf,hash,sameOrigin,json,readJSON} from '../../../server/security';
export async function GET(request:Request){const mode=new URL(request.url).searchParams.get('mode');try{if(mode==='key')return json({publicKey:verificationKey()});const owner=ownerOf(request),rpc=configuredRPC();if(!rpc)return json({error:'검토 저장소 설정이 필요합니다.'},503);if(mode==='pending'&&!roleOf(accountOf(request),'reviewer'))return json({error:'검토 담당자 계정이 필요합니다.'},403);if(mode==='mine'&&!owner)return json({error:'로그인이 필요합니다.'},401);const data=await rpc.call('bopok_review',{p_action:mode==='pending'?'pending':mode==='mine'?'mine':'approved',p_owner:owner??hash('public-review')});if(mode!=='mine'&&mode!=='pending')data.reviews=data.reviews.map((r:any)=>({...r,place:approvePlace(r.payload.place,r.id,r.verifiedAt)}));return json(data);}catch{return json({error:'검토 결과를 불러오지 못했습니다.'},503);}}
export async function POST(request:Request){if(!sameOrigin(request))return json({error:'잘못된 요청 출처입니다.'},403);const owner=ownerOf(request),rpc=configuredRPC();if(!owner||!accountOf(request)||!rpc)return json({error:'자료 검토에는 계정 로그인이 필요합니다.'},401);try{const body=z.discriminatedUnion('action',[z.object({action:z.literal('submit'),place:placeSchema}),z.object({action:z.enum(['approve','reject']),id:z.string().uuid()})]).parse(await readJSON(request,50000));if(!(await new TripStore(rpc).reserve(hash('review:'+owner),{scope:'review',minuteLimit:5,dailyRequests:quotaLimit('BOPok_REVIEW_DAILY_LIMIT',1000)})).allowed)return json({error:'검토 요청 한도에 도달했습니다.'},429);
 if(body.action==='submit'){const place=body.place;delete place.review;const facts=[place.walkMin,place.walkM,place.stairs,place.seat,place.foods,place.cost,place.hours,place.situations];if(!facts.some(f=>f.checked==='user')||facts.some(f=>f.nature!=='real'||f.value!==null&&(!f.collectedAt||Date.parse(f.collectedAt)>Date.now()||!/^https:\/\//.test(f.source))))return json({error:'실제 장소의 HTTPS 출처와 확인 날짜가 필요합니다.'},400);return json(await rpc.call('bopok_review',{p_action:'submit',p_owner:owner,p_payload:{placeId:place.id,placeName:place.name,place}}));}
 if(!roleOf(accountOf(request),'reviewer'))return json({error:'검토 담당자 계정이 필요합니다.'},403);const result=await rpc.call('bopok_review',{p_action:body.action,p_owner:owner,p_id:body.id});return json({...result,...(body.action==='approve'?{place:approvePlace(result.payload.place,result.id,result.verifiedAt)}:{})});
 }catch{return json({error:'자신의 기록은 승인할 수 없습니다. 기록 형식과 검토 상태를 확인해 주세요.'},400);}}
